### PR TITLE
Use syslog instead of print

### PR DESCRIPTION
**Pull request by afeena**
I used syslog for the first implementation. Maybe I should rewrite it with logging module?

### CODE REVIEW

**Comment by glaslos** [comment]
Sorry, I mislead you, I meant to use logging and then log to syslog.

**Comment by afeena** [comment]
Travis fails because of ``'dev/log'``. Maybe I'm doing something wrong with logger creation. I can mock server import in tests, but I don't like this solution. Maybe logger creation should be moved to another file or smth else... Can you give me some advice, please?

**Comment by glaslos** [comment]
Right, you need a syslog service running to make it work. Maybe just go for a rotating file logger: https://docs.python.org/3.5/library/logging.handlers.html#rotatingfilehandler

**Comment by afeena** [comment]
Thanks!

**Comment by glaslos** [comment]
No tests? :)

**Pull request merged**
