### PR TITLE
Log to MongoDB or Local JSON file

### PR DESCRIPTION
**Pull request by kevthehermit**
Adds the ability to log to a local json file or to a mongo db.

I plan to build a small web app that will visualise all the results in a similar style to kippo-graph and others.

### CODE REVIEW

**Comment by glaslos** [comment]
You need to add `pymongo` to https://github.com/mushorg/tanner/blob/master/requirements.txt to make the test work again.

**Comment by kevthehermit** [comment]
It seems to be upset by tthe entries in the config file.

**Comment by afeena** [comment]
You can simply mock config in the server tests

```
d=dict(MONGO= {'enabled': 'False', 'URI': 'mongodb://localhost'},
       LOCALLOG= {'enabled': 'False', 'PATH': '/tmp/tanner_report.json'})
m = mock.MagicMock()
m.__getitem__.side_effect = d.__getitem__
m.__iter__.side_effect = d.__iter__
config.TannerConfig.config = m
```

**Comment by kevthehermit** [comment]
Have never used mock before reading now to figure out where to put that :)

**Comment by afeena** [comment]
You need to put it somewhere in setUp function of the test_server.py :)

For example:
```
class TestServer(unittest.TestCase):
    def setUp(self):
        
         MOCK (copy/paste from previous message)
        
        @asyncio.coroutine
        def choosed(client):
            return [x for x in range(10)]

```

**Comment by kevthehermit** [comment]
All tests passing. Thank you very much :)

**Comment by glaslos** [comment]
Nice work! Do you think we should rename `LOGGER` to `FILELOG` as he is logging lines to `tanner.log` and `LOCALLOG` to `JSONLOG` to make the naming a bit more descriptive?
I wouldn't mind merging the PR as it is and do the changes later. @afeena what do you think?

**Comment by afeena** [comment]
@glaslos I totally agree :)
Great work, @kevthehermit!

**Pull request merged**
