### PR TITLE
Session manager improvements

### PR DESCRIPTION
**Pull request by afeena**
Initial improvements for session managing

Problem
-----------
See #353 for references.
`delete_old_session` was called for every request, which caused the freezing of TANNER.

Improvements
-----------------

1. Replace list with a dictionary for session storing: make it easier to check if session exists.
2. Run `delete_old_sessions` in a background aiohttp task, to make it independent from requests. Run every `delete_timeout` defined in config

### CODE REVIEW

**Comment by Fosocles** [comment]
Hi. I got "Unclosed client session\nclient_session: <aiohttp.client.ClientSession object at XXX>" error. Any ideas?

**Comment by afeena** [comment]
@Fosocles on which stage? When you run it? Close? Or with a specific request?

**Comment by afeena** [comment]
@Fosocles should work now

**Comment by Fosocles** [comment]
@afeena sorry for the late reply. I got the error when trying to start tanner. Will test the new version asap.

**Comment by afeena** [comment]
@Fosocles which python version are you using?

**Comment by t3chn0m4g3** [comment]
@afeena Just ran `dirb` four times in a row without any issues. Usually it took only one run for tanner to crash. Still have to check logging though. Keep you posted.
Thanks for the great work so far 😄

**Comment by afeena** [comment]
@t3chn0m4g3 Thanks for testing! please let me know if you find any problems :)
Still in TODO:
1. Fix tests
2. Check docker builds (I think I need to update config)

**Comment by t3chn0m4g3** [comment]
@afeena Do not worry about, Docker I will take care of it once you are done with this PR :)

**Comment by Fosocles** [comment]
@afeena Python3 v3.5.3

**Comment by afeena** [comment]
@Fosocles please use python 3.6, it was a mistake in README, now updated

**Comment by Fosocles** [comment]
Switched to v3.6, same errors. I might be doing something wrong somewhere.

**Comment by Fosocles** [comment]
Tried Python3.6 and Python 3.7 both on Debian 9 and Ubuntu 18.04 all to no success :'(

**Comment by t3chn0m4g3** [comment]
Logs are working perfectly fine. In production (T-Pot) it also looks good to me.
Thanks you!

**Comment by afeena** [comment]
@Fosocles show me please the exact  command you use to run tanner and full error log

**Comment by Fosocles** [comment]
@afeena Can't do this right now. I'll have to get back to you tomorrow morning. 
The command i use is "tanner" after i've started redis and the sandbox.

**Comment by Fosocles** [comment]
@t3chn0m4g3 are you going to update T-Pot's docker for Tanner?

**Comment by afeena** [comment]
@t3chn0m4g3 Thanks again for reporting and testing!

**Comment by t3chn0m4g3** [comment]
> @t3chn0m4g3 are you going to update T-Pot's docker for Tanner?
Yes

**Pull request merged**
