### PR TITLE
Prepare for new config.yaml

### PR DESCRIPTION
**Pull request by t3chn0m4g3**
I prepared the new `config.yaml` for docker, however when I run I get the following error regarding `DOCKER_HOST`:
```
tanner exited with code 1
tanner          |
tanner          |       _________    _   ___   ____________
tanner          |      /_  __/   |  / | / / | / / ____/ __ \
tanner          |       / / / /| | /  |/ /  |/ / __/ / /_/ /
tanner          |      / / / ___ |/ /|  / /|  / /___/ _, _/
tanner          |     /_/ /_/  |_/_/ |_/_/ |_/_____/_/ |_|
tanner          |
tanner          |
tanner          | Debug logs will be stored in /tmp/tanner/tanner.log
tanner          | Error logs will be stored in /tmp/tanner/tanner.err
tanner          | Data logs will be stored in /tmp/tanner/tanner_report.json
tanner          | Traceback (most recent call last):
tanner          |   File "/usr/bin/tanner", line 4, in <module>
tanner          |     __import__('pkg_resources').run_script('Tanner==0.6.0', 'tanner')
tanner          |   File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
tanner          |     self.require(requires)[0].run_script(script_name, ns)
tanner          |   File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1469, in run_script
tanner          |     exec(script_code, namespace, namespace)
tanner          |   File "/usr/lib/python3.7/site-packages/Tanner-0.6.0-py3.7.egg/EGG-INFO/scripts/tanner", line 35, in <module>
tanner          |   File "/usr/lib/python3.7/site-packages/Tanner-0.6.0-py3.7.egg/EGG-INFO/scripts/tanner", line 30, in main
tanner          |   File "/usr/lib/python3.7/site-packages/Tanner-0.6.0-py3.7.egg/tanner/server.py", line 31, in __init__
tanner          |   File "/usr/lib/python3.7/site-packages/Tanner-0.6.0-py3.7.egg/tanner/emulators/base.py", line 31, in __init__
tanner          |   File "/usr/lib/python3.7/site-packages/Tanner-0.6.0-py3.7.egg/tanner/emulators/lfi.py", line 9, in __init__
tanner          |   File "/usr/lib/python3.7/site-packages/Tanner-0.6.0-py3.7.egg/tanner/utils/aiodocker_helper.py", line 12, in __init__
tanner          |   File "/usr/lib/python3.7/site-packages/aiodocker/docker.py", line 94, in __init__
tanner          |     "Missing valid docker_host."
tanner          | ValueError: Missing valid docker_host.Either DOCKER_HOST or local sockets are not available.
```
Any ideas?

### CODE REVIEW

**Comment by t3chn0m4g3** [comment]
Is `tanner/data/` the default path for `config.yaml` when tanner is started or is there a command line option for the `config.yaml` I have to pass on?

**Comment by t3chn0m4g3** [comment]
Error remains 😦

**Comment by mzfr** [comment]
If you are talking about the docker error then it can be fixed by running `dockerd`  like `sudo dockerd` or you can start docker using `service` or `systemctl`.

**Comment by t3chn0m4g3** [comment]
@mzfr Thanks for your feedback, but I just setup the config as it was in the old `config.py` which was working perfectly fine without any errors regarding `DOCKER_HOST`.

**Comment by afeena** [comment]
@t3chn0m4g3 Thanks a lot!

```
EMULATOR_ENABLED:
<...>
  lfi: True
<...>
```

That cause the problem I guess :) since lfi uses docker

**Comment by t3chn0m4g3** [comment]
@afeena Args. How did I miss that 😱😇Thanks 🦅 👀. Will update tonight!

**Comment by t3chn0m4g3** [comment]
Ok, this works now perfectly fine.

**Comment by t3chn0m4g3** [comment]
Thanks!

**Pull request merged**
