### PR TITLE
Remove loop parameter, fixes #422

### LINKED ISSUE #422: Python 3.10 breaks Tanner
Tanner currently does not support Python 3.10 due to the `TypeError: As of 3.10, the *loop* parameter was removed from Queue() since it is no longer necessary`:
```
tanner          |
tanner          |       _________    _   ___   ____________
tanner          |      /_  __/   |  / | / / | / / ____/ __ \
tanner          |       / / / /| | /  |/ /  |/ / __/ / /_/ /
tanner          |      / / / ___ |/ /|  / /|  / /___/ _, _/
tanner          |     /_/ /_/  |_/_/ |_/_/ |_/_____/_/ |_|
tanner          |
tanner          |
tanner          | Debug logs will be stored in /tmp/tanner/tanner.log
tanner          | Error logs will be stored in /tmp/tanner/tanner.err
tanner          | Data logs will be stored in /var/log/tanner/tanner_report.json
tanner          | Traceback (most recent call last):
tanner          |   File "/usr/bin/tanner", line 4, in <module>
tanner          |     __import__('pkg_resources').run_script('Tanner==0.6.0', 'tanner')
tanner          |   File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 656, in run_script
tanner          |     self.require(requires)[0].run_script(script_name, ns)
tanner          |   File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1460, in run_script
tanner          |     exec(script_code, namespace, namespace)
tanner          |   File "/usr/lib/python3.10/site-packages/Tanner-0.6.0-py3.10.egg/EGG-INFO/scripts/tanner", line 37, in <module>
tanner          |   File "/usr/lib/python3.10/site-packages/Tanner-0.6.0-py3.10.egg/EGG-INFO/scripts/tanner", line 32, in main
tanner          |   File "/usr/lib/python3.10/site-packages/Tanner-0.6.0-py3.10.egg/tanner/server.py", line 22, in __init__
tanner          |   File "/usr/lib/python3.10/site-packages/Tanner-0.6.0-py3.10.egg/tanner/sessions/session_manager.py", line 13, in __init__
tanner          |   File "/usr/lib/python3.10/site-packages/Tanner-0.6.0-py3.10.egg/tanner/sessions/session_analyzer.py", line 15, in __init__
tanner          |   File "/usr/lib/python3.10/asyncio/queues.py", line 34, in __init__
tanner          |     super().__init__(loop=loop)
tanner          |   File "/usr/lib/python3.10/asyncio/mixins.py", line 17, in __init__
tanner          |     raise TypeError(
tanner          | TypeError: As of 3.10, the *loop* parameter was removed from Queue() since it is no longer necessary
```

### PR DESCRIPTION
**Pull request by t3chn0m4g3**
This fixes #422, however it also requires Python 3.10 to begin with.

### CODE REVIEW

**Comment by mzfr** [comment]
@t3chn0m4g3 Would this break if someone was using a Python version lower than 3.10? Also, have you made sure that this change doesn't break the functionality of the Queue and SessionAnalyzer? 

And just something for me, can you please link up the asyncio docs which says that the new version has removed the usage of the loop parameter?

**Comment by t3chn0m4g3** [comment]
@mzfr Yes, only 3.10 will be supported then. During 24h in production I did not see any issues, which is no guarantee, though 🙈

**Comment by mzfr** [comment]
@t3chn0m4g3 Yes that is the thing right now everything we have was tested properly with python 3.7 so now merging a change that works only with 3.10 might not be a good idea until everything is tested with 3.10.

Would you be willing to give an update about how things are going in your PROD in about a week? If all things stays stable then maybe we can go ahead and merge this PR

**Comment by t3chn0m4g3** [comment]
Meanwhile fixed with 2803c2773b8797d2632c6e36c6e5ea716b95c3b1 by @glaslos

**Pull request closed without merging**
