### PR TITLE
Add Cookie support for attacks

### PR DESCRIPTION
**Pull request by rnehra01**
@afeena Is it fine, or should I call `handle_cookies` in `emulate` method. I think this is better.
Tests will be fixed based on that.

### CODE REVIEW

**Comment by afeena** [comment]
@rnehra01 I don't think changing `emulate` method will be better. Keep this solution :)

**Comment by rnehra01** [comment]
There is one thing that might cause problems i.e presence of  `=` in cookies' values. Because we are extracting cookie data using `split('=')`.
One solution to it is that we should accept cookies with some sort of encoding, for simplicity `URL encode`.

**Comment by afeena** [comment]
How do you test cookie injection? :)
I try some simple cases and run sqlmap, but didn't get any result.
```[17:10:39] [WARNING] Cookie parameter 'sess_uuid' does not seem to be injectable```

**Comment by rnehra01** [comment]
Setting a cookie `id` = `1 and 1 --` is working for me.

**Comment by afeena** [comment]
Oh, I found some problems with setting some cookies in chrome. With Firefox it works well :)

**Comment by rnehra01** [comment]
resolve #150

**Pull request merged**
