### PR TITLE
optional postgress database #322

### PR DESCRIPTION
**Pull request by steve7158**
@glaslos @afeena please check this PR if it is relevant to issue #322

### CODE REVIEW

**Comment by glaslos** [comment]
Please adhere to PEP8 and I'd recommend to not use an ORM. Also I'd like to see more than just a database connection 😉

**Comment by steve7158** [comment]
Ok ill update you as soon as possible:+1:.

**Comment by afeena** [comment]
@steve7158 please use async for your implementation :)

**Comment by steve7158** [comment]
Ok, @afeena ill do that :smiley:  .

**Comment by steve7158** [comment]
its far from complete let me know if i am moving in a right track or not. :smile:

**Comment by steve7158** [comment]
also please let me know if it is a good practice or not to make PR commits that are incomplete. I thought it of as a way to review my code. Thank you

**Comment by glaslos** [comment]
It's fine and recommended if you work on a project for the first time. Now you already got important feedback that helps you preparing a solid PR

**Comment by steve7158** [comment]
I see thank you @glaslos

**Pull request closed without merging**
